#!/usr/bin/env python3
"""
Build the enemy sprite sheets.

    python3 tools/enemy_art/build.py            # write fpsgame1/EnemySpriteData.swift + previews
    python3 tools/enemy_art/build.py --preview  # previews only (build/enemy_art/*.png)

The Swift file is generated; edit the art modules (imp.py, ...) instead.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ROOT = os.path.dirname(os.path.dirname(HERE))

from pixelart import write_png, swift_sheet  # noqa: E402

SHEETS = []


def register(name, module_name):
    module = __import__(module_name)
    SHEETS.append((name, module))


register("imp", "imp")
try:
    register("demon", "demon")
except ImportError:
    pass
try:
    register("soldier", "soldier")
except ImportError:
    pass
try:
    register("baron", "baron")
except ImportError:
    pass


def main(argv):
    preview_only = "--preview" in argv
    out_dir = os.path.join(ROOT, "build", "enemy_art")
    os.makedirs(out_dir, exist_ok=True)

    swift_parts = []
    for name, module in SHEETS:
        frames = module.frames()
        w, h = module.W, module.H
        # preview rows: front 0-6, then each turn, then the death frames
        preview = frames[:7] + frames[10:] + frames[7:10] if len(frames) > 10 else frames
        write_png(os.path.join(out_dir, f"{name}.png"), preview, scale=3, cols=7)
        print(f"{name}: {len(frames)} frames of {w}x{h}")
        if not preview_only:
            swift_parts.append(swift_sheet(name, w, h, frames))

    if preview_only:
        return

    header = '''//
//  EnemySpriteData.swift
//  fpsgame1
//
//  GENERATED by tools/enemy_art/build.py — do not edit by hand.
//  Enemy sprite sheets authored as pixel art in tools/enemy_art/*.py and baked
//  here as run-length strings so the app still ships no image files.
//

// swiftlint:disable all

/// A sprite sheet stored as a shared palette plus one run-length string per frame.
/// Runs are `<count><code>`: the code is two letters indexing the palette
/// (first letter × 52 + second letter), or `.` for transparent.
struct BakedSpriteSheet {
    let width: Int
    let height: Int
    let palette: [UInt32]
    let frames: [String]

    static let alphabet: [Character] = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
    static let maxColors = alphabet.count * alphabet.count

    func decode() -> SpriteSheet {
        var letter: [Character: Int] = [:]
        for (i, ch) in Self.alphabet.enumerated() {
            letter[ch] = i
        }
        var decoded: [[UInt32]] = []
        decoded.reserveCapacity(frames.count)
        for frame in frames {
            var pixels: [UInt32] = []
            pixels.reserveCapacity(width * height)
            var count = 0
            var first: Int? = nil
            for ch in frame {
                if let hi = first {
                    let lo = letter[ch] ?? 0
                    let colorIndex = hi * Self.alphabet.count + lo
                    let color = colorIndex < palette.count ? palette[colorIndex] : 0
                    pixels.append(contentsOf: repeatElement(color, count: max(1, count)))
                    count = 0
                    first = nil
                } else if let digit = ch.wholeNumberValue, ch.isASCII {
                    count = count * 10 + digit
                } else if ch == "." {
                    pixels.append(contentsOf: repeatElement(0, count: max(1, count)))
                    count = 0
                } else {
                    first = letter[ch] ?? 0
                }
            }
            precondition(pixels.count == width * height, "baked frame has \\(pixels.count) pixels, expected \\(width * height)")
            decoded.append(pixels)
        }
        return SpriteSheet(frames: decoded, width: width, height: height)
    }
}

enum EnemySpriteData {
'''
    body = "\n\n".join(swift_parts)
    footer = "\n}\n"
    path = os.path.join(ROOT, "fpsgame1", "EnemySpriteData.swift")
    with open(path, "w") as f:
        f.write(header + body + footer)
    print(f"wrote {path} ({os.path.getsize(path) // 1024} KB)")


if __name__ == "__main__":
    main(sys.argv[1:])
