#!/usr/bin/env python3
"""
Build the baked sprite sheets (enemies, first-person weapons, pickups).

    python3 tools/sprite_art/build.py            # write fpsgame1/BakedSpriteData.swift + previews
    python3 tools/sprite_art/build.py --preview  # previews only (build/sprite_art/*.png)

The Swift file is generated; edit the art modules (imp.py, weapons.py, items.py, ...) instead.
portal.py is the design reference for the exit portal, which stays procedural in Textures.swift.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
ROOT = os.path.dirname(os.path.dirname(HERE))

from pixelart import write_png, swift_sheet  # noqa: E402

# (swift enum, sheet name, frames function, width, height, preview columns)
SHEETS = []


def register(group, name, module_name, frames_attr="frames", cols=7, args=()):
    module = __import__(module_name)
    fn = getattr(module, frames_attr)
    SHEETS.append((group, name, lambda: fn(*args), module.W, module.H, cols))


for enemy in ("imp", "demon", "soldier", "baron"):
    register("EnemySpriteData", enemy, enemy)
for weapon in ("fist", "pistol", "shotgun", "chaingun", "rocketLauncher"):
    register("WeaponSpriteData", weapon, "weapons", frames_attr="frames_for", cols=5, args=(weapon,))
register("ItemSpriteData", "items", "items", cols=7)


def main(argv):
    preview_only = "--preview" in argv
    out_dir = os.path.join(ROOT, "build", "sprite_art")
    os.makedirs(out_dir, exist_ok=True)

    groups = {}
    for group, name, make, w, h, cols in SHEETS:
        frames = make()
        # enemy previews: front 0-6, then each turn, then the death frames
        preview = frames[:7] + frames[10:] + frames[7:10] if len(frames) == 38 else frames
        scale = 3 if w <= 128 else 2
        write_png(os.path.join(out_dir, f"{name}.png"), preview, scale=scale, cols=cols)
        print(f"{name}: {len(frames)} frames of {w}x{h}")
        if not preview_only:
            groups.setdefault(group, []).append(swift_sheet(name, w, h, frames))

    if preview_only:
        return

    header = '''//
//  BakedSpriteData.swift
//  fpsgame1
//
//  GENERATED by tools/sprite_art/build.py — do not edit by hand.
//  Enemy, weapon and item sprite sheets authored as pixel art in
//  tools/sprite_art/*.py and baked here as run-length strings so the app still
//  ships no image files.
//

// swiftlint:disable all

/// A sprite sheet stored as a shared palette plus one run-length string per frame.
/// Runs are `<count><code>`: the code is two letters indexing the palette
/// (first letter × 52 + second letter), or `.` for transparent.
struct BakedSpriteSheet {
    let width: Int
    let height: Int
    let palette: [UInt32]
    let frames: [String]

    static let alphabet: [Character] = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")
    static let maxColors = alphabet.count * alphabet.count

    func decode() -> SpriteSheet {
        var letter: [Character: Int] = [:]
        for (i, ch) in Self.alphabet.enumerated() {
            letter[ch] = i
        }
        var decoded: [[UInt32]] = []
        decoded.reserveCapacity(frames.count)
        for frame in frames {
            var pixels: [UInt32] = []
            pixels.reserveCapacity(width * height)
            var count = 0
            var first: Int? = nil
            for ch in frame {
                if let hi = first {
                    let lo = letter[ch] ?? 0
                    let colorIndex = hi * Self.alphabet.count + lo
                    let color = colorIndex < palette.count ? palette[colorIndex] : 0
                    pixels.append(contentsOf: repeatElement(color, count: max(1, count)))
                    count = 0
                    first = nil
                } else if let digit = ch.wholeNumberValue, ch.isASCII {
                    count = count * 10 + digit
                } else if ch == "." {
                    pixels.append(contentsOf: repeatElement(0, count: max(1, count)))
                    count = 0
                } else {
                    first = letter[ch] ?? 0
                }
            }
            precondition(pixels.count == width * height, "baked frame has \\(pixels.count) pixels, expected \\(width * height)")
            decoded.append(pixels)
        }
        return SpriteSheet(frames: decoded, width: width, height: height)
    }
}

'''
    body = ""
    for group, parts in groups.items():
        body += f"enum {group} {{\n" + "\n\n".join(parts) + "\n}\n\n"
    path = os.path.join(ROOT, "fpsgame1", "BakedSpriteData.swift")
    with open(path, "w") as f:
        f.write(header + body)
    print(f"wrote {path} ({os.path.getsize(path) // 1024} KB)")


if __name__ == "__main__":
    main(sys.argv[1:])
